packages:
    - ./package
    - ./tests/*
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: false

catalogs:
    dev:
        "@types/node": ^25
        # Minimum supported version
        "tsdown": 0.21.0
    peer:
        # Supported versions
        "tsdown": ^0.21.0
    test:
        "vitest": ^5

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/*"
    - "@rolldown/*"
    - "rolldown"
    - "rolldown-plugin-dts"
    - "@tsdown/*"
    - "tsdown"
